name: data_analysis
channels:
  - conda-forge

dependencies:
  - python=3.11

  - numpy
  - pandas
  - scipy
  - matplotlib

  - xarray
  - netcdf4
  - h5netcdf
  - h5py

  - rasterio
  - rioxarray
  - geopandas
  - shapely
  - pyproj
  - fiona
  - cartopy
  - pyhdf

  - scikit-learn

  - libpysal
  - esda

  - dask
  - joblib
  - tqdm
  - zarr
  - requests
  - pyyaml

  - cdsapi

  - pip

  - pip:
      - pymannkendall